from tavily import TavilyClient
import re
from typing import Literal
from deepagents import create_deep_agent
from langchain.tools import tool
from parameters import kwargs
from langchain_ollama import OllamaEmbeddings
from langchain_chroma import Chroma
import os
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
import time
import WebRAG

load_dotenv()
folder_path = kwargs.get("folder_path")

PROGRAMMER_SYSTEM_PROMPT = """You are an expert programmer. Your task is to generate code according to requests.

Please ensure:
1. Do not include any specific symbols (e.g., ✓, →, ★) or emoji/emoticons in code.
2. Do not add BatchNorm (batch normalization layers) in neural networks.

You may use the following tools:
- internet_search: For web search.
- retrieve_context: To retrieve information."""

embedding = OllamaEmbeddings(model="nomic-embed-text")
vector_store=Chroma(
    collection_name="rag_collection",
    embedding_function=embedding,
    persist_directory="./chroma_rag_db"
)

@tool(response_format="content_and_artifact")
def retrieve_context(query: str):
    """Retrieve information to help answer a query"""
    retrieved_docs = vector_store.similarity_search(query, k=2)
    content = '\n\n'.join(
        (f"Source:{doc.metadata}\nContent:{doc.page_content}") for doc in retrieved_docs
    )
    return content,retrieved_docs

tavilyClient = TavilyClient()

@tool
def internet_search(
        query: str,
        max_results: int = 5,
        topic: Literal["general", "news", "finance"] = "general",
        include_raw_content: bool = False,
):
    """Run a web search"""
    return tavilyClient.search(
        query,
        max_results=max_results,
        include_raw_content=include_raw_content,
        topic=topic,
    )

programmer_agent = create_deep_agent(
    model="anthropic:claude-sonnet-4-5",
    system_prompt=PROGRAMMER_SYSTEM_PROMPT,
    tools=[internet_search, retrieve_context],
)

def Coding(fileName, QUERY):
    # 1. The network code has been generated
    file_names = [re.sub(r'[^\w\d]+', '', name.split('.')[0]) for name in os.listdir(folder_path)]

    for file_name in file_names:
        if fileName.lower() in file_name.lower():
            return f"The encoder code is already available and can be directly invoked from {fileName}.py."

    # 2. The network code needs to be generated by the agent
    StartTime = time.time()
    step = 1
    for event in programmer_agent.stream(
            {"messages": [{"role": "user",
                           "content": QUERY}]
             },
            stream_usage=True,
            stream_mode="values"
    ):
        msg = event["messages"][-1]
        msg.pretty_print()
        usage = getattr(msg, "usage_metadata", None)
        if usage:
            EndTime = time.time()
            print('😊Coder agent. Step:', step, ', consumes tokens:', usage["total_tokens"], ', running time:', EndTime-StartTime)
            step+=1
            StartTime = EndTime
        if "files" in event and len(event["files"]) > 0:
            file = open(folder_path + f"/{fileName}.py", "w+")
            file.truncate()
            for code in event["files"][f"/{fileName}.py"]["content"]:
                file.write(code)
                file.write("\n")
            file.close()